# Generated by Django 5.2.3 on 2025-06-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('visiteddate', models.DateTimeField(auto_now=True)),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('Prescriptionid', models.AutoField(primary_key=True, serialize=False)),
                ('presdate', models.DateField(auto_now=True)),
                ('medicine', models.TextField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Prescriptionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.prescription')),
            ],
        ),
    ]
